const responses = [
  { keyword: 'Hello', text: 'Hello! How can I assist you today?' },
  { keyword: 'Olá', text: 'Olá! Como posso ajudar você hoje?' },
  { keyword: 'Hi', text: 'Hi there! How can I assist you?' },
  { keyword: 'Oi', text: 'Oi! Como posso ajudar você?' },
  { keyword: 'Goodbye', text: 'Goodbye! Have a great day!' },
  { keyword: 'Tchau', text: 'Tchau! Tenha um ótimo dia!' },
  { keyword: 'Good', text: 'Good to hear! How can I help?' },
  { keyword: 'Bom', text: 'Fico feliz em ouvir isso! Como posso ajudar?' },
  { keyword: 'I want', text: 'Sure, I\'m here to help. What do you need?' },
  { keyword: 'Quero', text: 'Claro, estou aqui para ajudar. O que você precisa?' },
  { keyword: 'loan', text: 'Sure! Here are some options:\n1. Apply for a loan\n2. Loan conditions\n3. Help' },
  { keyword: 'empréstimo', text: 'Claro! Aqui estão algumas opções:\n1. Solicitar um empréstimo\n2. Condições do empréstimo\n3. Ajuda' },
  { keyword: '1', text: 'Great! Please fill out the loan application form.' },
  { keyword: '1', text: 'Ótimo! Por favor, preencha o formulário de solicitação de empréstimo.' },
  { keyword: '2', text: 'The loan conditions include a competitive interest rate and flexible repayment terms.' },
  { keyword: '2', text: 'As condições do empréstimo incluem uma taxa de juros competitiva e termos de pagamento flexíveis.' },
  { keyword: '3', text: 'How can I assist you further? Feel free to ask any questions.' },
  { keyword: '3', text: 'Como posso ajudar você ainda mais? Sinta-se à vontade para fazer perguntas.' },
  { keyword: 'loan', text: 'Would you like to apply for a loan? Click on the following link: [Loan Application](https://example.com/loan-application)' },
  { keyword: 'empréstimo', text: 'Gostaria de fazer um empréstimo? Clique no seguinte link: [Solicitação de Empréstimo](https://exemplo.com/solicitacao-emprestimo)' },
  { keyword: 'account', text: 'Are you interested in opening an account? Click on the following link: [Open Account](https://example.com/open-account)' },
  { keyword: 'conta', text: 'Está interessado em abrir uma conta? Clique no seguinte link: [Abrir Conta](https://exemplo.com/abrir-conta)' },
  { keyword: 'talk to an agent', text: 'Please wait for an agent to connect with you.' },
  { keyword: 'falar com um atendente', text: 'Por favor, aguarde até que um atendente entre em contato com você.' },
  { keyword: 'default', text: 'I\'m sorry, I didn\'t understand that. Here are some available options:\n1. Loan\n2. Account\n3. Talk to an agent' },
  { keyword: 'default', text: 'Desculpe, não entendi. Aqui estão algumas opções disponíveis:\n1. Empréstimo\n2. Conta\n3. Falar com um atendente' }
];

module.exports = responses;
